-   id: prettier
    name: prettier
    entry: prettier
    language: node
    files: \.(js)$
    args: ['--write', '--single-quote', '--trailing-comma', '--jsx-bracket-same-line']

    # Use additional_dependencies to install the actual node package
    minimum_pre_commit_version: 0.12.0
